### ISSUE TITLE
Empty export from "kubemq_pb.d.ts"

### ISSUE THREAD

**Issue by belizwp** [kubemq-io/kubemq-js#3]
I got this error when try to using the lib.
`
node_modules/kubemq-js/lib/queues.d.ts:256:84 - error TS2694: Namespace '"$HOME/my-app/node_modules/kubemq-js/lib/protos/index"' has no exported member 'StreamQueueMessagesResponse'.
`

then I found this file may cause it. which contain nothing but empty export.
```ts
export {};
//# sourceMappingURL=kubemq_pb.d.ts.map
```

seem like `src/protos/kubemq_pb.d.ts` does not included when you're building to lib.

**Comment by kubemq** [comment]
i have pushed a fix to it in release v1.2.2
Thank you !

**Comment by TECHNOFAB11** [comment]
This issue still exists, the file is "empty" on npmjs.org and when I try it locally, both are version 1.2.3

**Comment by TECHNOFAB11** [comment]
A workaround is to exclude "src/protos" in the tsconfig.json and using this as a build command for example: `tsc && cp src/protos/kubemq_* lib/protos`

**Comment by TECHNOFAB11** [comment]
@kubemq could you please reopen this? This unfortunately makes the library completely unusable in Typescript

**Comment by kubemq** [comment]
We will into that

**Comment by kubemq** [comment]
as a new lib is up and running. i'm closing this issue
